### ISSUE TITLE
Use of "covenant"

### ISSUE THREAD

**Issue by agrimm** [ContributorCovenant/contributor_covenant#257]
The word "covenant" very often has religious overtones. Many of the uses of covenant mentioned on Wikipedia's [disambiguation page](https://en.wikipedia.org/wiki/Covenant) refer to religious contexts. The use of this word this way may be alienating to people of various religious affiliations or lack thereof.

I read http://contributor-covenant.org/ , tried doing a google search for "Coraline Ada covenant", and also searched the Geek Feminism Wiki for covenant, but couldn't come up with any clarification of the context in which it's used.

Is the word meant to be used in a religious context?

**Comment by Aspie96** [comment]
(Yes I know this is old).

Coraline Ada also uses the word "sacred" for her own personal subjective opinions, so it is not surprising: http://blog.archive.org/2021/09/03/the-sacred-geometry-of-respect-trust-and-equity/

Signing a political document which also doubles as a pledge in order to join a community is quite cult-like. I don't see any issue with the wording.
