### ISSUE TITLE
lifestyle or creed?

### ISSUE THREAD

**Issue by postmodern** [ContributorCovenant/contributor_covenant#41]
> We are committed to making participation in this project a harassment-free experience for everyone, regardless of level of experience, gender, gender identity and expression, sexual orientation, disability, personal appearance, body size, race, age, or religion.

Would it be overkill to include "lifestyle"?

**Comment by krainboltgreene** [comment]
I would say those are both "choice" situations.

**Comment by doublezeta** [comment]
And religion is not?

**Comment by krainboltgreene** [comment]
Religion and some parts of personal appearance would also meet my "choice" criteria I think.

**Comment by doublezeta** [comment]
CODE_OF_CONDUCT.md doesn't mention "choice" as a criteria. Will you submit a pull request to clarify that harassment is tolerated in "choice" situations?

**Comment by postmodern** [comment]
Just because one chooses a certain lifestyle does not allow others to harass them, period. Religion is the obvious example, but what about vegetarianism, veganism, freeganism, car-free, anti-capitalist, DIY, etc lifestyles. Do these people not deserve our protection because they are somehow different from the authors of this CoC?

**Comment by krainboltgreene** [comment]
All I said was that those two examples you picked were choices. You two are extrapolating a lot from that.

**Comment by postmodern** [comment]
I think it goes back to the old debate of "born this way" vs. "choice". However, some wisely point out that it doesn't matter how one comes to a conclusion about their identity.

**Comment by postmodern** [comment]
I'm going to remove "politics", as some political ideologies are inherently oppressive.

**Comment by kerrizor** [comment]
Wiser people than us distilled this idea of "lifestyle and beliefs" or "imperative of living" down into "creed" - does that fit?

**Comment by doublezeta** [comment]
I don't think oppressive beliefs should warrant harassment either. Some people believe mainstream conservatism is oppressive, but there's tons of people who consider themselves conservatives. Imagine how shitty of a world we'd live in if they all had to live in fear of their lives.

**Comment by postmodern** [comment]
If creed is the canonical term, I'll go with it.

**Comment by postmodern** [comment]
@doublezeta I made a separate issue for politics. #73

**Comment by strand** [comment]
Hmm… I associate creed with "race, creed, or color" and specifically I believe creed extends to religious beliefs.

**Comment by kerrizor** [comment]
Sure.. I've seen it as "set of beliefs"

**Comment by strand** [comment]
I think key to this is we are specifying harassment-free space, and further specifying that this does not exclude people based on their beliefs, but their actions. Stating one's beliefs should not exclude people, harassing others based on one's beliefs should, and unfortunately making this line less fuzzy is hard.

**Comment by postmodern** [comment]
I think for a CoC to be effective, it should either be explicit or open ended. Listing some groups and some forms of harassment puts us in an awkward state somewhere between explicit and open ended. Either we should try to list as many groups as possible (so we do not make them invisible), or we should remove the line entirely and focus instead on forms of harassment.

**Comment by beoran** [comment]
I prefer "no matter who you are, or were you're from, or whatever opinions you may hold". Or "We welcome participation in this project by everyone who upholds this code." Or such.

Enumerations of characteristics that will not be discriminated against to consideration are silly, they tend to reinforce stereotype rather than lessen them, and of course, there's always something missing from the list since people are infinitely diverse.  Postmodern is right about one thing. Only actual behaviour within the context of the project matters.

**Comment by kerrizor** [comment]
@beoran I sometimes feel the same way - "Why don't we just talk about behavior instead of a never inclusive enough list?" I'm reminded, however, that one benefit to having the list is to emphasize and/or highlight system abuses and lack of access to privilege that far too many people endure.

We list specific behaviors in order clarify what we see as problematic, and there's no reason we can't do the same for enumerating a non-exhaustive list of groups. Sometimes the simple acknowledgement of a struggle is a solid first step towards creating a greater environment of respect and safety.

**Comment by beoran** [comment]
@kerrizor While idealistically speaking such a list might feel encouraging for people who feel they are "on" it, it might equally be discouraging to those who are not "on" it. 

Besides, this CoC is only for people like you and me who are already amongst the economically advantaged: we have a programmable computer and an internet connection. Economic disadvantage is the rot of all other disadvantages and just putting people on a list of tags won't change a thing about that. 

Furthermore, since this CoC is likely to be a legally binding document upon the maintainers of a FLOSS project in the USA, we have to think very deeply about the ramifications of the wording used. Unfortunately there are plenty of people who would like to use a text such as the CoC against the maintainers of a FLOSS project, to put pressure or to extort damages. That is why such a document cannot be adapted without proper care. But that is the topic of another issue here.

I agree that a non-exhaustive list would be better than what is there now. It would be an idea to add "... or any other personal characteristic unrelated to this project" or such to the end to make it so. Now, hover, the list is closed, and this means that legally and technically speaking it IS ok to discriminate against people for reasons NOT mentioned in the list. Too bad for the Inuit who likes to eat seals, the Chinese Communist Party member, the Japanese whose father is a whaler, the Kansas girl who likes to carry a concealed gun, ... By the way, for similar reasons, the USA Constitution has a non-enumerated rights clause as well.

Which brings me to another problem. The list as it is now is self-contradictory. If you do not discriminate against sexual preference, you discriminate against about 1 billion people who are bound by their religious dogma to profess that not being heterosexual is a sin. Since the text is likely to be legally binding in the USA, this could cause a catch 22 where the project's maintainers may be forced to pay damages to both sides if a conflict between, say an Islamic and a homosexual person breaks out in the forums.

**Comment by krainboltgreene** [comment]
> Besides, this CoC is only for people like you and me who are already amongst the economically advantaged

What? That's definitely not true.

**Comment by krainboltgreene** [comment]
Read the rest of the comment, suggest removing it. There's no value in intellectual dishonesty here.

**Comment by postmodern** [comment]
I'm going to close this. I've lost interest and life-style lacks a generally accepted definition.

**Comment by beoran** [comment]
How will someone without a programmable computer (or at least a computing device) and internet access contribute to a FLOSS project? Or even read this CoC? It's impossible for them. That is what I mean. 

And before you accuse me of intellectual dishonesty, might I have the courtesy of  to actually answer my points?

**Comment by kerrizor** [comment]
@beoran "Respond to me or I will accuse you of something regardless of the truth of the matter" isn't really a welcome, constructive response. If you'd like to continue this thread, let's take it elsewhere.

**Comment by beoran** [comment]
@kerizor 

Ok, I admit that that's not very "welcoming". Neither was krainboltgreene's reply constructive nor welcoming though. What comes around goes around, you see. But yes, let's not continue here. I will refrain from any more comments on this issue. If krainboltgrene has the mind to continue the discussion I welcome him to contact me directly.

**Comment by tripu** [comment]
> I'm going to remove "politics", as some political ideologies are inherently oppressive (ex: anything in the nationalist/fascist part of the spectrum).

@postmodern, as much as I despise nationalisms of any kind, I think you are wrong: at least in several Western European countries, nationalists are a large and mostly civil segment of the population, not an inherently violent bunch.

Besides, if someone classifies nationalism as &ldquo;inherently oppressive&rdquo;, the door is open to exclude almost any other view: communists, socialists, anarchists, nativists, etc.

The expression of political views should be either strictly banned from team interactions, or completely respected. I strongly support the latter.
