### ISSUE TITLE
Why should I use Contributor Covenant..?

### ISSUE THREAD

**Issue by sirsnowy7** [ContributorCovenant/contributor_covenant#414]
I just don't get the point of using this rather than creating my own or simply not having one? GitHub users aren't very rude or annoying, generally.

**Comment by victimsofgaybullying** [comment]
@sirsnowy7 
#538

Because pedophiles and OTO.org kiddy sex cult members need to exclude anyone who does like sex with children from open source projects they are involved in. The author of this document is in an Alesiter Crowley the great beast 666 pedo cult that is jailing people for religious vilification without trial in Australia and just last month the lesbians cheered on the child sex cult doing this.

That's right @CoralineAda is an admitted member of the OTO.org child sex cult. See the #538 list. I backed it up. She's so done. 

http://www.greaterthancode.com/podcast/075-code-and-witchcraft/


https://www.buzzfeed.com/lanesainty/a-man-was-awarded-19000-after-a-woman-posted-a-youtube

https://archive.4plebs.org/pol/thread/135163177/ 

The pedophiles are winning. You can be thrown in jail without a court apperence like "Legg Devine" on austlii.edu.au case law was for "religious vilification" of the Great Beast 666's (crowley he callled himself that when he wasn't writing poems about sodomizing little boys called "Ballard to Passive Pederasty")
http://archive.is/fhk8p

http://acat.act.gov.au/__data/assets/pdf_file/0005/985730/CRISTIAN_v_BOTTRILL_Appeal_2016_ACAT_104-2.pdf see section 41
http://www.courts.act.gov.au/__data/assets/pdf_file/0019/1002673/Cristian.pdf
http://www.canberratimes.com.au/act-news/blogger-ordered-to-remove-hate-speech-against-member-of-small-religious-order-20180316-h0xkch.html
http://acat.act.gov.au/__data/assets/pdf_file/0005/1176035/BOTTRILL-v-SUNOL-Discrimination-2018-ACAT-21.pdf
http://bernardgaynor.com.au/freedom-australia-just-taken-another-hit/
^^ Must See ^^
http://www.canberratimes.com.au/act-news/blogger-ordered-to-remove-hate-speech-against-member-of-small-religious-order-20180316-h0xkch.html
The case law lies and doesn't say the judge was switched 3 times back and forwards, there was more than one judge or they ordered a whole blog of anti-paedophilia activism censored. After the court removed the "hate speech" against the cult of infant sex normalization and child sex magick rituals the mainstream media says how evil I am for not loving sex with children.
https://voat.co/v/pizzagate/2015620
https://voat.co/v/pizzagate/2029702

Just google Aleister Crowley sex cult guardian newspaper to see what the Mainstream news in America talks about this cult that believes in drinking blood (spirit cooking aka cakes of light) , Child sacrifice and more.
