### ISSUE TITLE
Anti-sex-work and corporate-coddling issues

### ISSUE THREAD

**Issue by SoniEx2** [ContributorCovenant/contributor_covenant#867]
The Code of Conduct prevents it from being used in anything sex-work-related, which seems to be primarily designed to coddle corporations.

Sexualized projects are more effective than AGPLv3 at keeping corporations away because AGPLv3 can be easily handled but sexual harassment claims would be a lot harder to deal with. (Combining both is of course more effective.) However, content warnings may provide a path forward here. But, we still hate corps tbh. :)

Anyway, can the code of conduct be amended to allow our explicitly anti-corporate, pro-sex-worker projects? [The old FreeBSD code of conduct](http://web.archive.org/web/20200530031745/https://www.freebsd.org/internal/code-of-conduct.html) handled this but they switched their code of conduct at some point for some reason. It's kinda hard to do sex tech when others refuse to allow it.

**Comment by CoralineAda** [comment]
Contributor Covenant is released under a Creative Commons license (https://github.com/ContributorCovenant/contributor_covenant/blob/release/LICENSE.md) and I always encourage community leaders to adapt it to their particular needs. That makes the code of conduct stronger, because it brings alignment with that community's unique culture and values.

I'd be interested in seeing how your particular adaptation turns out, so please share a link sometime in the future?
